Game predictions
stevegardiner26/famble pull request #15
Opened 2020-11-26 04:26 UTC by stevegardiner26

Added the backend route that allows for fetching the odds of games.

2020-11-27 19:07 UTC, ranajay5699 requested changes
the betmodal has been deprecated, please merge master into your branch and make the same changes you made for the bet service calls

2020-11-27 19:11 UTC, PRamos1196 approved these changes

2020-11-27 21:37 UTC, VivekSreenivasan approved these changes

2020-12-01 22:23 UTC, PRamos1196 approved these changes

2020-12-02 04:24 UTC, ranajay5699 approved these changes

2020-12-02 04:25 UTC, merged